import { useSession } from "next-auth/react";
import Head from "next/head";
import CheckSteamId from "../components/element/checkSteamId";

const Home = () => {
  const { data: session } = useSession();
 
  return (
    <>
      <Head>
        <title>Dongalytics | Dota 2 Stats | Dedicated to the So Pure Guild</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col py-10 items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 pb-12 pt-3 ">
          <h1 className="text-5xl text-black font-extrabold tracking-tight sm:text-[5rem]">
            Dong<span className="text-primary">alytics</span>
          </h1>  
        </div>
        { session && <CheckSteamId /> }
      </div>
    </>
  );
};

export default Home;
