import Head from "next/head";
import Link from "next/link";

const HomePage = () => {

  return (
    <>
      <Head>
        <title>Dongalytics | Dota 2 Stats | Dedicated to the So Pure Guild</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto max-w-screen-xl px-4 py-32 lg:flex lg:h-screen lg:items-center">
        <div className="mx-auto max-w-xl text-center">
          <h1 className="text-3xl font-extrabold sm:text-5xl">
            The Real Way..
            <strong className="font-extrabold text-indigo-600 sm:block">
              To Measure Your Dong (turbo)
            </strong>
          </h1>

          <p className="mt-4 sm:text-xl sm:leading-relaxed">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt illo
            tenetur fuga ducimus numquam ea!
          </p>

          <div className="mt-8 flex flex-wrap justify-center gap-4">
            <Link
              className="group relative inline-block focus:outline-none focus:ring"
              href="/login"
            >
              <span
                className="absolute inset-0 translate-x-1.5 translate-y-1.5 bg-indigo-500 transition-transform group-hover:translate-y-0 group-hover:translate-x-0"
              ></span>

              <span
                className="relative inline-block border-2 border-current px-8 py-3 text-sm font-bold uppercase tracking-widest text-black group-active:text-opacity-75"
              >
                Get Started
              </span>
            </Link>

            <Link
              className="group relative inline-block focus:outline-none focus:ring"
              href="/about"
            >
              <span
                className="absolute inset-0 translate-x-1.5 translate-y-1.5 bg-indigo-500 transition-transform group-hover:translate-y-0 group-hover:translate-x-0"
              ></span>

              <span
                className="relative inline-block border-2 border-current px-8 py-3 text-sm font-bold uppercase tracking-widest text-black group-active:text-opacity-75"
              >
                Learn More
              </span>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default HomePage;
